[2022-09-17 13:53:01,759] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2022-09-17T13:52:45.916211+00:00 [queued]>
[2022-09-17 13:53:01,772] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2022-09-17T13:52:45.916211+00:00 [queued]>
[2022-09-17 13:53:01,772] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 13:53:01,772] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-17 13:53:01,772] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 13:53:01,789] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2022-09-17 13:52:45.916211+00:00
[2022-09-17 13:53:01,794] {standard_task_runner.py:52} INFO - Started process 340 to run task
[2022-09-17 13:53:01,797] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2022-09-17T13:52:45.916211+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp8dtr66az', '--error-file', '/tmp/tmp9gnn0ir9']
[2022-09-17 13:53:01,805] {standard_task_runner.py:80} INFO - Job 11: Subtask store_user
[2022-09-17 13:53:01,897] {task_command.py:369} INFO - Running <TaskInstance: user_processing.store_user manual__2022-09-17T13:52:45.916211+00:00 [running]> on host 9f5a23719b96
[2022-09-17 13:53:02,013] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2022-09-17T13:52:45.916211+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-17T13:52:45.916211+00:00
[2022-09-17 13:53:02,015] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2022-09-17 13:53:02,029] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-09-17 13:53:02,035] {python.py:173} INFO - Done. Returned value was: None
[2022-09-17 13:53:02,055] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20220917T135245, start_date=20220917T135301, end_date=20220917T135302
[2022-09-17 13:53:02,106] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-17 13:53:02,157] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
